### PR TITLE
Compatibility with Swift 4.2

### PR DESCRIPTION
**Pull request by Coeur**
This makes the code compatible with all 4.x versions of Swift.

### CODE REVIEW

**Comment by pmusolino** [comment]
Any news on this? @devxoul When you have plan to release on cocoapods?

**Comment by Coeur** [comment]
@pmusolino while personally I wait for Xcode 10.1 stable to start publishing using Swift 4.2 due to [an Apple bug regarding iOS 9 compatibility](https://stackoverflow.com/q/52364231/1033581), I understand that not yet having this Toaster fix being published is frustrating.

You may workaround it by specifying a branch or commit in your Podfile:

    pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'

**Comment by talk2cerlin** [comment]
@Coeur Specifying commit would be better than specifying branch as cocoapod may take a broken commit from master

**Comment by Coeur** [comment]
@talk2cerlin last commit is from **Jun 10, 2018**. I've tried contacting devxoul both on GitHub and Facebook without success. It may be time to consider a fork like done by hujiaju: https://github.com/devxoul/Toaster/issues/139#issuecomment-443966412

**Comment by devxoul** [comment]
[Toaster 2.2.0](https://github.com/devxoul/Toaster/releases/tag/2.2.0) supports both Swift 4.2 and Swift 5.0. Sorry for being late 🙏

**Pull request merged**
