### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by achernoprudov**
Swift Package Manager support added. Linked with issue #179

### CODE REVIEW

**Comment by vapor-pawelw** [comment]
Is this getting merged anytime soon?

**Comment by achernoprudov** [comment]
I think this repository is no longer supported. So I would recommend to migrate on different approach or write the custom one. If you have legacy project and you really need SPM - you could use mine repository and specify ‘SPM’ branch.

**Comment by cozzin** [comment]
@devxoul @Coeur Could you merge this PR?

**Comment by adamTL** [comment]
> @devxoul @Coeur Could you merge this PR?

Would love SPM capability! PR looks clean.

**Review by sheshnathiicmr — APPROVED** [review]

**Comment by Coeur** [comment]
I don't work on the project anymore. But on popular demand, I'm merging this PR.

**Pull request merged**
