### PR TITLE
Changes methods' input (and attributes) to NSAttributedString.

### PR DESCRIPTION
**Pull request by vitchor**
Very simple update to start supporting attributedText.

### CODE REVIEW

**Comment by vitchor** [comment]
Ok. I've just fixed that, @Coeur – all public functions still work with a regular text input now (besides the attributedText).

**Comment by vitchor** [comment]
@Coeur, do you know if this will be merged soon? Thanks :)

**Comment by Coeur** [comment]
It will not. My previous comment is still valid: that feature could be achieved without breaking the existing API, meaning by keeping the signatures of existing functions and variables, and being strictly additive for NSAttributedString support, like it's done on a UILabel for instance.

**Comment by Coeur** [comment]
Superseded by #157

**Pull request closed without merging**
