### PR TITLE
Fix isShowing to be set from iOS 13 and above

### PR DESCRIPTION
**Pull request by cozzin**
This PR solves #166

### CODE REVIEW

**Comment by Coeur** [comment]
Good idea.
Just to confirm, you've test it with Xcode 11 beta 6?

**Comment by cozzin** [comment]
@Coeur Yes, I tested it in with `Xcode11 beta 6` & `10.3`

**Comment by Coeur** [comment]
Well, this time I'll try Twitter: https://twitter.com/adigitalknight/status/1164516525937553408

**Comment by cozzin** [comment]
@Coeur Oh!! Thank you :)

**Pull request merged**
