### PR TITLE
Added aditional required switch cases

### PR DESCRIPTION
**Pull request by DominatorVbN**
Changed minimum target version to iOS 9.0 suggested by cocoa pod

### CODE REVIEW

**Comment by mircobabini** [comment]
Great job. Please, accept this pull request.

**Comment by tylerdwolff** [comment]
Can we please has this PR merged soon. I love using this in project.

**Comment by vandyks** [comment]
Bump for the merge.

**Comment by muehlemann** [comment]
@devxoul can you please merge and create a new release?

**Comment by Coeur** [comment]
I can merge, but I'm not doing any release for Toaster, as I'm no longer an active maintainer.

**Pull request merged**
