### PR TITLE
Fix issue of keyboard hiding toasts on iOS 11 (imperfect: work in progress)

### PR DESCRIPTION
**Pull request by Coeur**
This solution for #117 just **works**. No crash. 🎉
Demo included for testing (see #134 for the Demo change alone).

### CODE REVIEW

**Comment by devxoul** [comment]
Sadly it has a UI glitch. The keyboard will cover the toast if the toast in presented before the keyboard shows. But I think what you've done with overriding `addSubview()` is clever. I updated #124 PR with using some of your idea. I'd be glad if you could check t

**Comment by Coeur** [comment]
@devxoul, I cannot reproduce the glitch you're mentioning. But maybe adding an observer on keyboardWillShowName would be enough so solve it.

**Comment by devxoul** [comment]
Actually there are two.

1. Previous toast is covered by the keyboard.

    toaster1

2. The toast disappears without animations after the keyboard disappears.

    toaster2

**Comment by Coeur** [comment]
@devxoul About the animation, you're correct, which means that your solution to keep a reference to `originalSubviews` is a required step, together with registering to keyboardDidHideName or keyboardWillHideName.

Regarding the toast being covered, and the glitch you have on your keyboard, I'm curious to know which version of Xcode and iOS you're using.

**Comment by Coeur** [comment]
Closing this one, as #124 is better.

**Pull request closed without merging**
