### PR TITLE
Add keyboard observer

### PR DESCRIPTION
**Pull request by cozzin**
Add keyboard observer for observing keyboard state from app launch.

### CODE REVIEW

**Comment by Coeur** [comment]
Note also [this Pull Request](https://github.com/pmusolino/Wormholy/pull/52) where they use two independant tricks:

a. `__attribute__((constructor))` instead of `+load` in Objective-C, to allow application startup loading in extensions/categories, and as such avoiding the potential need for a singleton class.

b. `extension UIApplication {
     override open var next: UIResponder? {
        /* Called before applicationDidFinishLaunching */
        UIApplication.runOnce;
        return super.next
    }
}` trick in Swift, which should be enough to add application UI observers.

**Comment by cozzin** [comment]
@Coeur Thank you, I didn't know about this tricks.

**Comment by cozzin** [comment]
@Coeur I change to use UIApplication trick at 063b380. It works great!

**Comment by cozzin** [comment]
@Coeur Could you merge this PR?

**Comment by devxoul** [comment]
@Coeur hey, I'd like to add you as an owner of the CocoaPods trunk. Can you send your email address to devxoul@gmail.com so that I can execute the command below?

```
$ pod trunk add-owner Toaster YOUR_EMAIL
```

**Comment by Coeur** [comment]
Email send a minute ago at xx:41 (depending on your time zone).

**Comment by devxoul** [comment]
@Coeur I've added you as an co-owner of Toaster! I really appreciate of your work :clap:

**Pull request merged**
